# 模型设置
model_name_or_path: ../model/Qwen2.5-VL-3B-Instruct
auto_model_class: "Qwen2_5_VLForConditionalGeneration"
torch_dtype: bfloat16

# 数据集设置
train_dataset_name: ./data/train.jsonl
test_dataset_name: ./data/test.jsonl
preprocessing_num_workers: 1
data_collator: "Qwen2_5VLCollator"
max_seq_length: 256
max_image_side: 256

# 训练超参数
seed: 2025
data_seed: 2025
remove_unused_columns: False
# 训练次数
per_device_train_batch_size: 1
gradient_accumulation_steps: 1
max_steps: 1500
# 学习率相关
learning_rate: 1.0e-5
lr_scheduler_type: cosine
warmup_ratio: 0.1
# 训练效率
gradient_checkpointing: false
bf16: true
bf16_full_eval: true
# 验证输出
eval_strategy: steps
eval_steps: 0.1
metric_for_best_model: "eval_loss"
greater_is_better: false
# 结果输出
output_dir: ../model/Qwen2.5-VL-3B-Instruct-X
save_strategy: "no"
report_to: swanlab
logging_first_step: true
logging_steps: 0.01
